<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>
    
    <PropertyGroup>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AcoustID.NET" Version="1.3.3" />
      <PackageReference Include="CliFx" Version="2.3.6" />
      <PackageReference Include="Dapper" Version="2.1.72" />
      <PackageReference Include="DapperBulkQueries.Npgsql" Version="1.9001.512" />
      <PackageReference Include="dbup-postgresql" Version="7.0.1" />
      <PackageReference Include="DiscogsConnect" Version="4.1.1" />
      <PackageReference Include="FFMpegCore" Version="5.4.0" />
      <PackageReference Include="FuzzySharp" Version="2.0.2" />
      <PackageReference Include="Inflatable.Lastfm" Version="1.2.0" />
      <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.5" />
      <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Npgsql" Version="10.0.2" />
      <PackageReference Include="Polly" Version="8.6.6" />
      <PackageReference Include="Quartz" Version="3.16.1" />
      <PackageReference Include="RestSharp" Version="114.0.0" />
      <PackageReference Include="ShuffleList" Version="1.0.0" />
      <PackageReference Include="SmartFormat" Version="3.6.1" />
      <PackageReference Include="SoundCloudExplode" Version="1.6.7" />
      <PackageReference Include="SoundFingerprinting" Version="14.1.0" />
      <PackageReference Include="Spectre.Console" Version="0.54.0" />
      <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.4.2" />
      <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.9" />
      <PackageReference Include="TagLibSharp" Version="2.3.0" />
      <PackageReference Include="z440.atl.core" Version="7.11.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <None Update="DbScripts\20250608 spotify indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250608 deezer.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250612 deezer indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250625 spotify indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250622 indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250629 indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250710 indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250711 indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250713 tidal index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250912 discogs tables.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250921 musicbrainz index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250924 tidal index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250928 discogs master tables.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20250929 tidal index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20251109 get_tag_value function.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20251109 metadata remove columns.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20251110 index sortname musicbrainz.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20251228 index discogs release title.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20251230 submit acoustid.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260124 tidal similartracks.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260127 artists index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260127 albums index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260127 metadata index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260214 tidal similar artists.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260214 tidal similar albums.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260222 fix primary keys.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260329 musicbrainz index.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260404 soundcloud tables.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260411 soundcloud indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260412 update metadata table.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260415 artists ext table.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\1000 init db.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260417 add lastfm tables.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260606 soundcloud indexes.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260615 add mood tables.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\approachability_3c-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\approachability_3c-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\danceability-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\danceability-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\engagement_3c-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\engagement_3c-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\engagement_regression-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\engagement_regression-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\gender-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\gender-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\genre_discogs400-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\genre_discogs400-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_acoustic-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_acoustic-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_aggressive-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_aggressive-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_electronic-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_electronic-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_happy-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_happy-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_party-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_party-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_relaxed-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_relaxed-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_sad-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\mood_sad-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\timbre-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\timbre-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\voice_instrumental-discogs-effnet-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\voice_instrumental-discogs-effnet-1.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="MachineLearningModels\discogs-effnet.onnx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="DbScripts\20260629 update mood tables.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="DbScripts\20260124 tidal similartracks.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Compile>
    </ItemGroup>

</Project>
